name: actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        gcc_version: [12]
        compiler: ['make']

    steps:
    - uses: actions/checkout@v3

    - name: Compile using make
      if: matrix.compiler == 'make'
      run: |
        cd src
        make
        cd ..
      shell: bash

    - name: Run
      run: |
          cd testing
          ../src/stride pdb1fmc.pdb > pdb1fmc.out
          ../src/stride pdb1mjh.pdb > pdb1mjh.out
          ../src/stride pdb1res.pdb > pdb1res.out
          ../src/stride pdb2btm.pdb > pdb2btm.out
          diff pdb1fmc.out pdb1fmc_original.out
          diff pdb1mjh.out pdb1mjh_original.out
          diff pdb1res.out pdb1res_original.out
          diff pdb2btm.out pdb2btm_original.out
          cd ..
      shell: bash
