name: actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
        gcc_version: [11, 12]
        compiler: ['make']

    steps:
    - uses: actions/checkout@v3
    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: ${{ matrix.gcc_version }}

    - name: Compile using make
      if: matrix.compiler == 'make'
      run: |
        ./configure
        make
      shell: bash

    - name: Run
      run: |
          cd testing
          ../src/stride pdb1fmc.pdb > pdb1fmc.out
          ../src/stride pdb1mjh.pdb > pdb1mjh.out
          ../src/stride pdb1res.pdb > pdb1res.out
          ../src/stride pdb1btm.pdb > pdb1btm.out
          diff pdb1fmc.out pdb1fmc_original.out
          diff pdb1mjh.out pdb1mjh_original.out
          diff pdb1res.out pdb1res_original.out
          diff pdb1btm.out pdb1btm_original.out
          cd ..
      shell: bash
